import streamlit as st
import subprocess
import configparser
import os
import ast
import pandas as pd
import matplotlib.pyplot as plt
import sys

st.set_page_config(layout="wide", page_title="DOP-SQL Interface")

# --- Header ---
st.title("DOP-SQL: Differentially Private SQL System")
st.markdown("A General-purpose, High-utility, and Extensible Private SQL System")

# --- Layout: Two columns for Inputs ---
col1, col2 = st.columns([1.2, 1])

with col1:
    st.subheader("1. Input Query")
    default_query = """select count(*) from supplier, lineitem, orders, customer, nation where supplier.S_SUPPKEY=lineitem.L_SUPPKEY and lineitem.L_ORDERKEY=orders.O_ORDERKEY and orders.O_CUSTKEY=customer.C_CUSTKEY and customer.C_NATIONKEY=nation.N_NATIONKEY and nation.N_NATIONKEY=supplier.S_NATIONKEY;
"""

    query = st.text_area("SQL Query", default_query, height=250)
    relations_input = st.text_input(
        "Primary Private Relations (comma-separated)", "customer"
    )

with col2:
    st.subheader("2. Parameter Configuration")

    st.markdown("**Global Parameters**")
    col2a, col2b = st.columns(2)
    with col2a:
        epsilon = st.number_input(
            "Privacy Budget (ε)", min_value=0.01, max_value=10.0, value=1.0, step=0.1
        )
    with col2b:
        beta = st.number_input(
            "Error Probability (β)",
            min_value=0.001,
            max_value=1.0,
            value=0.1,
            step=0.01,
        )

    p_num = st.number_input("Processor Count (Parallelism)", min_value=1, value=5)
    recursion_bound = st.number_input("Recursion Bound", min_value=1, value=3)
    with st.expander("Advanced Algorithm Parameters", expanded=False):
        c1, c2 = st.columns(2)
        with c1:
            fast_global_sensitivity = st.number_input(
                "FastSJA global_sensitivity", min_value=0, value=1000000
            )
            fast_approximate_factor = st.number_input(
                "FastSJA approximate_factor", min_value=0.0, value=0.0, format="%f"
            )
            delta = st.number_input(
                "Relaxation (δ) [MultiQ]", min_value=0.0, value=0.000001, format="%f"
            )
        with c2:
            max_upper_bound = st.number_input(
                "MaxSJA upper_bound", min_value=1, value=200
            )
            error_level = st.number_input(
                "Error Level [MaxSJA]", min_value=0.01, value=0.1
            )

# --- Execution ---
st.divider()

if st.button("Execute DP-SQL Query", type="primary"):
    with st.spinner("Rewriting query and applying DP mechanisms..."):

        # 1. Prepare temporary files for main.py execution
        with open("ui_test_query.txt", "w") as f:
            f.write(query)

        with open("ui_test_relations.txt", "w") as f:
            f.write("\n".join([r.strip() for r in relations_input.split(",")]))

        # 2. Generate configuration file dynamically
        config = configparser.ConfigParser()
        config.read("config/parameter.config")  # Load base config to keep DB defaults

        if not config.has_section("global"):
            config.add_section("global")
        config.set("global", "epsilon", str(epsilon))
        config.set("global", "beta", str(beta))
        config.set("global", "processor_num", str(p_num))
        config.set("global", "recursion_bound", str(recursion_bound))

        if not config.has_section("FastSJA"):
            config.add_section("FastSJA")
        # Use values from UI (defaults provided above)
        config.set("FastSJA", "global_sensitivity", str(fast_global_sensitivity))
        config.set("FastSJA", "approximate_factor", str(fast_approximate_factor))

        if not config.has_section("MultiQ"):
            config.add_section("MultiQ")
        config.set("MultiQ", "delta", str(delta))

        if not config.has_section("MaxSJA"):
            config.add_section("MaxSJA")
        config.set("MaxSJA", "error_level", str(error_level))
        config.set("MaxSJA", "upper_bound", str(max_upper_bound))

        with open("ui_parameter.config", "w") as f:
            config.write(f)

        # 3. Call the existing backend (main.py)
        cmd = [
            sys.executable,
            "main.py",
            "--d",
            "config/database.ini",
            "--q",
            "ui_test_query.txt",
            "--r",
            "ui_test_relations.txt",
            "--c",
            "ui_parameter.config",
            "--o",
            "ui_out.txt",
            "--debug",
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            st.error("Execution Failed. Check database connection and syntax.")
            st.code(result.stderr)
        else:
            # 4. Parse the output text file generated by main.py
            with open("ui_out.txt", "r") as f:
                output_content = f.read()

            st.success("Query Evaluated Successfully!")

            # Extract metrics directly from the text file output
            out_lines = output_content.split("\n")
            q_type = (
                out_lines[0].replace("Query type:", "").strip()
                if len(out_lines) > 0
                else "Unknown"
            )

            true_res_str = ""
            noise_res_str = ""

            for line in out_lines:
                if line.startswith("true result:"):
                    true_res_str = line.split("true result:")[1].strip()
                if line.startswith("noise result:"):
                    noise_res_str = line.split("noise result:")[1].strip()

            # --- Visualization (Mirroring Fig 2c of the paper) ---
            st.subheader(f"3. Results Overview (Mechanism: {q_type})")

            try:
                # Try to parse python lists if output is group-by (e.g. [(val1, grp1), (val2, grp2)])
                true_vals = ast.literal_eval(true_res_str)
                noise_vals = ast.literal_eval(noise_res_str)

                if (
                    isinstance(true_vals, list)
                    and len(true_vals) > 0
                    and isinstance(true_vals[0], tuple)
                ):
                    # Group by query
                    df = pd.DataFrame(
                        {
                            "Group": [str(x[1]) for x in true_vals],
                            "True Result": [float(x[0]) for x in true_vals],
                            "Privatized Result": [float(x[0]) for x in noise_vals],
                        }
                    ).set_index("Group")

                    st.bar_chart(df)
                else:
                    # Single Aggregate
                    st.metric(
                        "Privatized Output",
                        f"{float(noise_vals):,.4f}",
                        delta=f"True: {float(true_vals):,.4f}",
                        delta_color="off",
                    )

            except Exception as e:
                # Fallback if output parsing fails (shows raw logs)
                st.warning(
                    "Could not parse result for Bar Chart visualization. Displaying raw output."
                )
                st.text(output_content)

            with st.expander("View Debug Logs / Rewritten Query"):
                st.code(output_content)

            # Cleanup temp files
            for temp_file in [
                "ui_test_query.txt",
                "ui_test_relations.txt",
                "ui_parameter.config",
                "ui_out.txt",
            ]:
                if os.path.exists(temp_file):
                    os.remove(temp_file)
