import subprocess
import configparser
import os
import ast
import re
import sys
import pandas as pd
import argparse


def parse_output(output_content):
    """
    Parses the out.txt content generated by main.py
    and extracts metrics along with calculating relative errors.
    """
    out_lines = output_content.split("\n")

    q_type = "Unknown"
    for line in out_lines:
        if line.startswith("Query type:"):
            q_type = line.replace("Query type:", "").strip()
            break

    true_res_str, noise_res_str = "", ""
    rewrite_time_str, process_time_str = "N/A", "N/A"

    for line in out_lines:
        if line.startswith("true result:"):
            true_res_str = line.split("true result:")[1].strip()
        if line.startswith("noise result:"):
            noise_res_str = line.split("noise result:")[1].strip()
        if line.startswith("rewrite time:"):
            rewrite_time_str = line.split("rewrite time:")[1].strip()
        if line.startswith("process time:"):
            process_time_str = line.split("process time:")[1].strip()

    # Clean numpy types formatting
    if true_res_str:
        true_res_str = re.sub(r"np\.float64\((.*?)\)", r"\1", true_res_str)
    if noise_res_str:
        noise_res_str = re.sub(r"np\.float64\((.*?)\)", r"\1", noise_res_str)

    rel_error = None
    try:
        true_vals = ast.literal_eval(true_res_str)
        noise_vals = ast.literal_eval(noise_res_str)

        # If result is a list of tuples (e.g., from Group By queries)
        if (
            isinstance(true_vals, list)
            and len(true_vals) > 0
            and isinstance(true_vals[0], tuple)
        ):
            errors = []
            for t, n in zip(true_vals, noise_vals):
                t_val = float(t[0])
                n_val = float(n[0])
                if t_val != 0:
                    errors.append(abs(t_val - n_val) / abs(t_val))
                else:
                    errors.append(0)
            # Calculate Average Relative Error for Group By
            rel_error = sum(errors) / len(errors) if errors else 0
        else:
            # Single aggregate result
            true_val_f = float(true_vals)
            noise_val_f = float(noise_vals)
            if true_val_f != 0:
                rel_error = abs(true_val_f - noise_val_f) / abs(true_val_f)
            else:
                rel_error = 0
    except Exception:
        pass  # Leaving relative error as None if unparsable

    return {
        "query_type": q_type,
        "true_result": true_res_str,
        "noise_result": noise_res_str,
        "relative_error": rel_error,
        "rewrite_time": rewrite_time_str,
        "process_time": process_time_str,
    }


def run_experiment(
    query_file, relation_file, base_config_file, section, param, values, output_csv
):
    """
    Runs the main.py pipeline over a list of parameter values, logs them,
    and exports them to a CSV.
    """
    print(f"Starting evaluation: Varying {section}.{param} for {query_file}")
    results = []

    config = configparser.ConfigParser()
    config.read(base_config_file)

    for val in values:
        print(f"  -> Testing {param} = {val}...", end="", flush=True)

        # Add section if not present & set specific config variable
        if not config.has_section(section):
            config.add_section(section)
        config.set(section, param, str(val))

        # Temporary config/output files specifically for evaluating
        temp_config = f"temp_eval_{param}.config"
        temp_out = f"temp_eval_out_{param}.txt"

        with open(temp_config, "w") as f:
            config.write(f)

        cmd = [
            sys.executable,
            "main.py",
            "--d",
            "config/database.ini",
            "--q",
            query_file,
            "--r",
            relation_file,
            "--c",
            temp_config,
            "--o",
            temp_out,
            "--debug",
        ]

        # Run main.py with modified configs
        run_result = subprocess.run(cmd, capture_output=True, text=True)

        if os.path.exists(temp_out):
            with open(temp_out, "r") as f:
                out_content = f.read()

            parsed = parse_output(out_content)
            parsed["changed_parameter"] = param
            parsed["parameter_value"] = val
            parsed["success"] = run_result.returncode == 0
            if not parsed["success"]:
                parsed["error_log"] = run_result.stderr.strip()

            results.append(parsed)
            os.remove(temp_out)
            print(" Done")
        else:
            print(" Failed")
            results.append(
                {
                    "changed_parameter": param,
                    "parameter_value": val,
                    "success": False,
                    "error_log": run_result.stderr.strip(),
                }
            )

        if os.path.exists(temp_config):
            os.remove(temp_config)

    # Dump to CSV
    df = pd.DataFrame(results)

    # Reorder columns slightly for better readability
    cols = [
        "success",
        "changed_parameter",
        "parameter_value",
        "query_type",
        "relative_error",
        "true_result",
        "noise_result",
        "rewrite_time",
        "process_time",
    ]
    # add remaining columns (like error_log if any failed)
    cols.extend([c for c in df.columns if c not in cols])
    df = df[cols]

    df.to_csv(output_csv, index=False)
    print(f"Results successfully saved to {output_csv}\n")


if __name__ == "__main__":
    # --- Example 1: Vary Epsilon for a Nested Query ---
    run_experiment(
        query_file="test_rec.txt",
        relation_file="test_relation.txt",
        base_config_file="config/parameter.config",
        section="global",
        param="epsilon",
        values=[0.1, 0.2, 0.5, 0.75, 1.0, 2.0, 5.0, 10.0],
        output_csv="eval_rec6_epsilon.csv",
    )

    # # --- Example 2: Vary Recursion Bound for a Recursive Query ---
    # # Using 'test.txt' as a placeholder since it might contain a recursive statement
    # run_experiment(
    #     query_file="test_rec.txt",
    #     relation_file="test_relation.txt",
    #     base_config_file="config/parameter.config",
    #     section="global",
    #     param="recursion_bound",
    #     values=[2, 3, 4, 5],
    #     output_csv="eval_recursion_bound.csv",
    #
